version: "3.9"

x-networks: &x-networks
  networks:
    - backend

networks:
  backend:

services:
  db:
    <<: *x-networks
    image: bitnami/postgresql:13
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_DATABASE: app
      POSTGRESQL_PASSWORD: postgres
